name: unit test

on:
  push:
    branches: [ "master", "master8.3" ]
  pull_request:
    branches: [ "master", "master8.3" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up PHP 8.0
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0

    - name: Install librdkafka and rdkafka extension
      run: |
        sudo apt-get install -y librdkafka-dev
        sudo pecl install rdkafka
        echo "extension=rdkafka.so" >> $(php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||")

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run test suite
      run: composer run-script test
